(require 'color-theme)



(defun color-theme-dark-hron ()
  "Color theme by Aleksei Gusev, created 2009-05-20."
  (interactive)
  (color-theme-install
   '(color-theme-dark-hron
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "cyan")
      (foreground-color . "white")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "red")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 123 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (anything-header ((t (:box nil :foreground "grey90" :background "grey20"))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (better-fringes-bitmap ((t (:foreground "khaki"))))
     (better-fringes-important-bitmap ((t (:foreground "red"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "chocolate1"))))
     (change-log-conditionals ((t (:foreground "LightGoldenrod"))))
     (change-log-date ((t (:foreground "LightSalmon"))))
     (change-log-email ((t (:foreground "LightGoldenrod"))))
     (change-log-file ((t (:foreground "LightSkyBlue"))))
     (change-log-function ((t (:foreground "LightGoldenrod"))))
     (change-log-list ((t (:foreground "Cyan1"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "PaleGreen"))))
     (compilation-error ((t (:bold t :foreground "Pink" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "LightGoldenrod"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 106 :width normal :foundry "xos4" :family "Terminus"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "cyan"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:foreground "cyan" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:foreground "cyan1" :underline t :height 0.8))))
     (diary ((t (:foreground "yellow1"))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-flagged ((t (:bold t :foreground "Pink" :weight bold))))
     (dired-header ((t (:foreground "PaleGreen"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "Aquamarine"))))
     (dired-marked ((t (:bold t :foreground "Pink" :weight bold))))
     (dired-perm-write ((t (:foreground "chocolate1"))))
     (dired-symlink ((t (:foreground "Cyan1"))))
     (dired-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (dropdown-list-face ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :background "lightyellow" :foreground "black" :height 123))))
     (dropdown-list-selection-face ((t (:foreground "black" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "DejaVu Sans Mono" :background "purple" :height 123))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (emms-browser-album-face ((t (:foreground "#aaaaff" :height 1.1))))
     (emms-browser-artist-face ((t (:foreground "#aaaaff" :height 1.3))))
     (emms-browser-track-face ((t (:foreground "#aaaaff" :height 1.0))))
     (emms-browser-year/genre-face ((t (:foreground "#aaaaff" :height 1.5))))
     (emms-playlist-selected-face ((t (:foreground "SteelBlue3"))))
     (emms-playlist-track-face ((t (:foreground "DarkSeaGreen"))))
     (emms-stream-name-face ((t (:bold t :weight bold))))
     (emms-stream-url-face ((t (:foreground "LightSteelBlue"))))
     (erb-comment-delim-face ((t (:foreground "lightgreen"))))
     (erb-comment-face ((t (:foreground "lightgreen"))))
     (erb-delim-face ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (erb-exec-delim-face ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (erb-exec-face ((t (:background "#383838"))))
     (erb-face ((t (:background "#383838"))))
     (erb-out-delim-face ((t (:background "#383838" :foreground "#aaffff"))))
     (erb-out-face ((t (:background "#383838"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (ffap ((t (:background "darkolivegreen"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "Firebrick4"))))
     (flymake-warnline ((t (:background "DarkBlue"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "chocolate1"))))
     (font-lock-comment-face ((t (:foreground "chocolate1"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "Cyan1"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "PaleGreen"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "grey10"))))
     (git-header-face ((t (:foreground "blue"))))
     (git-ignored-face ((t (:foreground "grey40"))))
     (git-mark-face ((t (:bold t :foreground "tomato" :weight bold))))
     (git-permission-face ((t (:bold t :foreground "green" :weight bold))))
     (git-separator-face ((t (:foreground "brown"))))
     (git-status-face ((t (:foreground "salmon"))))
     (git-unknown-face ((t (:bold t :foreground "goldenrod" :weight bold))))
     (git-unmerged-face ((t (:bold t :foreground "red" :weight bold))))
     (git-uptodate-face ((t (:foreground "grey40"))))
     (gnus-group-mail-1 ((t (:bold t :foreground "#e1ffe1" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "#e1ffe1"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "DarkSeaGreen1" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "DarkSeaGreen1"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-low ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine2"))))
     (gnus-group-news-1 ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-splash ((t (:foreground "#cccccc"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "pink"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "Sans Serif"))))
     (hi-blue ((t (:background "light blue" :foreground "black"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:background "green1" :foreground "black"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-mumamo-black-b ((t (:bold t :underline t :weight bold))))
     (hi-mumamo-blue ((t (:underline "light blue"))))
     (hi-mumamo-blue-b ((t (:bold t :underline "blue1" :weight bold))))
     (hi-mumamo-green ((t (:underline "green1"))))
     (hi-mumamo-green-b ((t (:bold t :underline "green1" :weight bold))))
     (hi-mumamo-pink ((t (:underline "pink"))))
     (hi-mumamo-red-b ((t (:bold t :underline "red1" :weight bold))))
     (hi-mumamo-yellow ((t (:underline "yellow1"))))
     (hi-pink ((t (:background "pink" :foreground "black"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1" :foreground "black"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highlight-changes ((t (:foreground "red1"))))
     (highlight-changes-delete ((t (:foreground "red1" :underline t))))
     (holiday ((t (:background "chocolate4"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Pink"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (isearch ((t (:bold t :background "dark blue" :weight bold))))
     (isearch-fail ((t (:background "dark red"))))
     (iswitchb-current-match ((t (:foreground "LightSkyBlue"))))
     (iswitchb-invalid-regexp ((t (:bold t :foreground "Pink" :weight bold))))
     (iswitchb-single-match ((t (:foreground "chocolate1"))))
     (iswitchb-virtual-matches ((t (:foreground "LightSteelBlue"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "dark blue"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
		 (magit-item-highlight ((t (:background "gray7"))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mlinks-link ((t (:underline t :foreground "cyan1"))))
     (mode-line ((t (:background "#483D8B" :foreground "white" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :box (:line-width -1 :color "grey40") :weight light))))
     (mouse ((t (:background "black"))))
     (mumamo-background-chunk-major ((t (nil))))
     (mumamo-background-chunk-submode1 ((t (:background "dark slate gray"))))
     (mumamo-background-chunk-submode2 ((t (:background "DarkOrhid4"))))
     (mumamo-background-chunk-submode3 ((t (:background "dark slate gray"))))
     (mumamo-background-chunk-submode4 ((t (:background "DarkOrhid4"))))
     (mumamo-border-face-in ((t (:italic t :bold t :foreground "LightSteelBlue" :underline t :slant italic :weight bold))))
     (mumamo-border-face-out ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (next-error ((t (:background "blue3"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "LightGoldenrod"))))
     (nxml-attribute-prefix ((t (:foreground "LightSteelBlue"))))
     (nxml-attribute-value ((t (:foreground "LightSalmon"))))
     (nxml-attribute-value-delimiter ((t (:foreground "LightSalmon"))))
     (nxml-cdata-section-CDATA ((t (:foreground "LightSteelBlue"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "Aquamarine"))))
     (nxml-char-ref-number ((t (:foreground "Aquamarine"))))
     (nxml-comment-content ((t (:foreground "chocolate1"))))
     (nxml-comment-delimiter ((t (:foreground "chocolate1"))))
     (nxml-delimited-data ((t (:foreground "LightSalmon"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "LightSkyBlue"))))
     (nxml-element-prefix ((t (:foreground "LightSteelBlue"))))
     (nxml-entity-ref-delimiter ((t (:foreground "Aquamarine"))))
     (nxml-entity-ref-name ((t (:foreground "Aquamarine"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc" :family "fixed"))))
     (nxml-hash ((t (:foreground "LightSteelBlue"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "LightSteelBlue"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "LightGoldenrod"))))
     (nxml-namespace-attribute-value ((t (:foreground "LightSalmon"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "LightSalmon"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "LightSteelBlue"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "unknown" :family "DejaVu Sans Mono" :box 1 :height 123))))
     (nxml-outline-ellipsis ((t (:bold t :family "DejaVu Sans Mono" :foundry "unknown" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :weight bold :height 123))))
     (nxml-outline-indicator ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 123))))
     (nxml-processing-instruction-content ((t (:foreground "LightSalmon"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "Cyan1"))))
     (nxml-prolog-keyword ((t (:foreground "Cyan1"))))
     (nxml-prolog-literal-content ((t (:foreground "LightSalmon"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "LightSalmon"))))
     (nxml-ref ((t (:foreground "Aquamarine"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (outline-1 ((t (:foreground "LightSkyBlue"))))
     (outline-2 ((t (:foreground "LightGoldenrod"))))
     (outline-3 ((t (:foreground "Cyan1"))))
     (outline-4 ((t (:foreground "chocolate1"))))
     (outline-5 ((t (:foreground "PaleGreen"))))
     (outline-6 ((t (:foreground "Aquamarine"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "LightSalmon"))))
     (proced-mark ((t (:foreground "Aquamarine"))))
     (proced-marked ((t (:bold t :foreground "Pink" :weight bold))))
     (proced-sort-header ((t (:foreground "Cyan1"))))
     (query-replace ((t (:bold t :background "dark blue" :weight bold))))
     (rcirc-bright-nick ((t (:foreground "Aquamarine"))))
     (rcirc-dim-nick ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 106 :width normal :foundry "xos4" :family "Terminus"))))
     (rcirc-keyword ((t (:background "darkolivegreen"))))
     (rcirc-my-nick ((t (:foreground "LightSkyBlue"))))
     (rcirc-nick-in-message ((t (:foreground "Cyan1"))))
     (rcirc-nick-in-message-full-line ((t (:bold t :weight bold))))
     (rcirc-other-nick ((t (:foreground "LightGoldenrod"))))
     (rcirc-prompt ((t (:foreground "cyan1"))))
     (rcirc-server ((t (:foreground "chocolate1"))))
     (rcirc-server-prefix ((t (:foreground "chocolate1"))))
     (rcirc-timestamp ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 106 :width normal :foundry "xos4" :family "Terminus"))))
     (rcirc-track-keyword ((t (:bold t :weight bold))))
     (rcirc-track-nick ((t (nil))))
     (rcirc-url ((t (:bold t :weight bold))))
     (region ((t (:background "dark blue"))))
     (rng-error ((t (:bold t :weight bold :foreground "Pink"))))
     (rngalt-validation-header-bottom ((t (:background "RGB:87/CE/FA" :foreground "white"))))
     (rngalt-validation-header-top ((t (:background "white" :foreground "RGB:87/CE/FA"))))
     (rst-level-1-face ((t (:background "grey85"))))
     (rst-level-2-face ((t (:background "grey78"))))
     (rst-level-3-face ((t (:background "grey71"))))
     (rst-level-4-face ((t (:background "grey64"))))
     (rst-level-5-face ((t (:background "grey57"))))
     (rst-level-6-face ((t (:background "grey50"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (sgml-namespace ((t (:foreground "LightSteelBlue"))))
     (sh-escaped-newline ((t (:foreground "LightSalmon"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "dark blue"))))
     (show-paren-mismatch ((t (:background "dark red"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition ((t (:foreground "orange"))))
     (woman-bold ((t (:bold t :foreground "green2" :weight bold))))
     (woman-italic ((t (:italic t :underline t :slant italic))))
     (woman-unknown ((t (:foreground "cyan1"))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/mirror-highlight-face ((t (:background "gray22")))))))