(require 'color-theme)

(defun color-theme-dark-hron ()
  "Color theme by Aleksei Gusev, created 2010-04-04."
  (interactive)
  (color-theme-install
   '(color-theme-dark-hron
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "cyan")
      (foreground-color . "white")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "red")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (erc-button-face . erc-button)
      (erc-button-mouse-face . highlight)
      (erc-button-nickname-face . erc-nick-default-face)
      (ibuffer-deletion-face . font-lock-type-face)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . font-lock-warning-face)
      (ibuffer-title-face . font-lock-type-face)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (markdown-blockquote-face . font-lock-comment-face)
      (markdown-bold-face . font-lock-type-face)
      (markdown-header-face . font-lock-function-name-face)
      (markdown-inline-code-face . font-lock-builtin-face)
      (markdown-italic-face . font-lock-variable-name-face)
      (markdown-link-face . font-lock-constant-face)
      (markdown-list-face . font-lock-variable-name-face)
      (markdown-math-face . font-lock-builtin-face)
      (markdown-reference-face . font-lock-type-face)
      (markdown-url-face . font-lock-string-face)
      (org-goto-interface . outline)
      (org-remember-interactive-interface . refile)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight)
      (anything-isearch-match . isearch))
     (anything-header ((t (:background "grey20" :foreground "grey90" :box nil))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (better-fringes-bitmap ((t (:foreground "khaki"))))
     (better-fringes-important-bitmap ((t (:foreground "red"))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (breakpoint-disabled ((t (:foreground "grey70"))))
     (breakpoint-enabled ((t (:bold t :foreground "red1" :weight bold))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "chocolate1"))))
     (change-log-conditionals ((t (:foreground "LightGoldenrod"))))
     (change-log-date ((t (:foreground "LightSalmon"))))
     (change-log-email ((t (:foreground "LightGoldenrod"))))
     (change-log-file ((t (:foreground "LightSkyBlue"))))
     (change-log-function ((t (:foreground "LightGoldenrod"))))
     (change-log-list ((t (:foreground "Cyan1"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "PaleGreen"))))
     (compilation-error ((t (:bold t :foreground "Pink" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "LightGoldenrod"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "cyan"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:foreground "cyan" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:foreground "cyan1" :underline t :height 0.8))))
     (diary ((t (:foreground "yellow1"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey70"))))
     (diff-file-header ((t (:bold t :background "grey60" :weight bold))))
     (diff-function ((t (:background "grey45"))))
     (diff-header ((t (:background "grey45"))))
     (diff-hunk-header ((t (:background "grey45"))))
     (diff-index ((t (:bold t :weight bold :background "grey60"))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey60"))))
     (diff-refine-change ((t (:background "grey60"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-flagged ((t (:bold t :foreground "Pink" :weight bold))))
     (dired-header ((t (:foreground "PaleGreen"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "Aquamarine"))))
     (dired-marked ((t (:bold t :foreground "Pink" :weight bold))))
     (dired-perm-write ((t (:foreground "chocolate1"))))
     (dired-symlink ((t (:foreground "Cyan1"))))
     (dired-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (ditz-issue-id-face ((t (:bold t :foreground "PowderBlue" :underline t :weight bold))))
     (ditz-release-name-face ((t (:bold t :foreground "red" :underline t :weight bold))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 123 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 123 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (ediff-current-diff-A ((t (:bold t :background "#3c3c3c" :weight bold))))
     (ediff-current-diff-Ancestor ((t (:bold t :background "#3c3c14" :weight bold))))
     (ediff-current-diff-B ((t (:bold t :background "#3c3c34" :weight bold))))
     (ediff-current-diff-C ((t (:bold t :background "#3c3c2c" :weight bold))))
     (ediff-even-diff-A ((t (:background "#3c3c3c"))))
     (ediff-even-diff-Ancestor ((t (:background "#3c3c14"))))
     (ediff-even-diff-B ((t (:background "#3c3c34"))))
     (ediff-even-diff-C ((t (:background "#3c3c2c"))))
     (ediff-fine-diff-A ((t (:bold t :background "#3c3c1c" :weight bold))))
     (ediff-fine-diff-Ancestor ((t (:bold t :background "#3c3c24" :weight bold))))
     (ediff-fine-diff-B ((t (:bold t :background "#3c3c04" :weight bold))))
     (ediff-fine-diff-C ((t (:bold t :background "#3c3c0c" :weight bold))))
     (ediff-odd-diff-A ((t (:background "#3c3c1c"))))
     (ediff-odd-diff-Ancestor ((t (:background "#3c3c24"))))
     (ediff-odd-diff-B ((t (:background "#3c3c04"))))
     (ediff-odd-diff-C ((t (:background "#3c3c0c"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (emms-browser-album-face ((t (:foreground "#aaaaff"))))
     (emms-browser-artist-face ((t (:bold t :foreground "#aaaaff" :weight bold))))
     (emms-browser-track-face ((t (:foreground "#aaaaff"))))
     (emms-browser-year/genre-face ((t (:foreground "#aaaaff"))))
     (emms-playlist-selected-face ((t (:foreground "SteelBlue3"))))
     (emms-playlist-track-face ((t (:foreground "DarkSeaGreen"))))
     (emms-stream-name-face ((t (:bold t :weight bold))))
     (emms-stream-url-face ((t (:foreground "LightSteelBlue"))))
     (erb-comment-delim-face ((t (:foreground "lightgreen"))))
     (erb-comment-face ((t (:foreground "lightgreen"))))
     (erb-delim-face ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (erb-exec-delim-face ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (erb-exec-face ((t (:background "#383838"))))
     (erb-face ((t (:background "#383838"))))
     (erb-out-delim-face ((t (:background "#383838" :foreground "#aaffff"))))
     (erb-out-face ((t (:background "#383838"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-button ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:foreground "red"))))
     (erc-fool-face ((t (:foreground "dim gray"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-keyword-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-pal-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (ffap ((t (:background "darkolivegreen"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "Firebrick4"))))
     (flymake-warnline ((t (:background "DarkBlue"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "chocolate1"))))
     (font-lock-comment-face ((t (:foreground "chocolate1"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "Cyan1"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "PaleGreen"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "grey10"))))
     (git-header-face ((t (:foreground "blue"))))
     (git-ignored-face ((t (:foreground "grey40"))))
     (git-mark-face ((t (:bold t :foreground "tomato" :weight bold))))
     (git-permission-face ((t (:bold t :foreground "green" :weight bold))))
     (git-separator-face ((t (:foreground "brown"))))
     (git-status-face ((t (:foreground "salmon"))))
     (git-unknown-face ((t (:bold t :foreground "goldenrod" :weight bold))))
     (git-unmerged-face ((t (:bold t :foreground "red" :weight bold))))
     (git-uptodate-face ((t (:foreground "grey40"))))
     (gnus-group-mail-1 ((t (:bold t :foreground "#e1ffe1" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "#e1ffe1"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "DarkSeaGreen1" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "DarkSeaGreen1"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-low ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine2"))))
     (gnus-group-news-1 ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-splash ((t (:foreground "#cccccc"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "pink"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (haml-tab-face ((t (:background "hotpink"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "Sans Serif"))))
     (hi-blue ((t (:background "light blue" :foreground "black"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:background "green1" :foreground "black"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-mumamo-black-b ((t (:bold t :underline t :weight bold))))
     (hi-mumamo-blue ((t (:underline "light blue"))))
     (hi-mumamo-blue-b ((t (:bold t :underline "blue1" :weight bold))))
     (hi-mumamo-green ((t (:underline "green1"))))
     (hi-mumamo-green-b ((t (:bold t :underline "green1" :weight bold))))
     (hi-mumamo-pink ((t (:underline "pink"))))
     (hi-mumamo-red-b ((t (:bold t :underline "red1" :weight bold))))
     (hi-mumamo-yellow ((t (:underline "yellow1"))))
     (hi-pink ((t (:background "pink" :foreground "black"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1" :foreground "black"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highlight-changes ((t (:foreground "red1"))))
     (highlight-changes-delete ((t (:foreground "red1" :underline t))))
     (hl-paren-face ((t (nil))))
     (holiday ((t (:background "chocolate4"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Pink" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-menu-header ((t (:bold t :weight bold :family "Sans Serif"))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :height 1.728 :family "Sans Serif"))))
     (info-title-2 ((t (:bold t :weight bold :height 1.44 :family "Sans Serif"))))
     (info-title-3 ((t (:bold t :weight bold :height 1.2 :family "Sans Serif"))))
     (info-title-4 ((t (:bold t :weight bold :family "Sans Serif"))))
     (info-xref ((t (:foreground "cyan1" :underline t))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:bold t :background "dark blue" :weight bold))))
     (isearch-fail ((t (:background "dark red"))))
     (iswitchb-current-match ((t (:foreground "LightSkyBlue"))))
     (iswitchb-invalid-regexp ((t (:bold t :foreground "Pink" :weight bold))))
     (iswitchb-single-match ((t (:foreground "chocolate1"))))
     (iswitchb-virtual-matches ((t (:foreground "LightSteelBlue"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "dark blue"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (magit-branch ((t (:bold t :weight bold))))
     (magit-diff-add ((t (:foreground "white"))))
     (magit-diff-del ((t (:foreground "OrangeRed"))))
     (magit-diff-file-header ((t (nil))))
     (magit-diff-hunk-header ((t (:italic t :slant italic))))
     (magit-diff-none ((t (nil))))
     (magit-header ((t (nil))))
     (magit-item-highlight ((t (:background "gray17"))))
     (magit-item-mark ((t (:foreground "orange"))))
     (magit-log-head-label ((t (:background "DarkGreen"))))
     (magit-log-tag-label ((t (:background "DarkGoldenRod"))))
     (magit-section-title ((t (:bold t :weight bold))))
     (makefile-makepp-perl ((t (:background "DarkBlue"))))
     (makefile-shell ((t (nil))))
     (makefile-space ((t (:background "hotpink"))))
     (makefile-targets ((t (:foreground "LightSkyBlue"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mlinks-link ((t (:foreground "cyan1" :underline t))))
     (mode-line ((t (:foreground "#acbc90" :background "#1e2320" :box (:color "#1e2320" :line-width 2)))))
     (mode-line-inactive ((t (:background "#2e3330" :foreground "#88b090" :box (:color "#2e3330" :line-width 2)))))
     (mouse ((t (:background "black"))))
     (mumamo-background-chunk-major ((t (nil))))
     (mumamo-background-chunk-submode1 ((t (:background "dark slate gray"))))
     (mumamo-background-chunk-submode2 ((t (:background "DarkOrhid4"))))
     (mumamo-background-chunk-submode3 ((t (:background "dark slate gray"))))
     (mumamo-background-chunk-submode4 ((t (:background "DarkOrhid4"))))
     (mumamo-border-face-in ((t (:italic t :bold t :foreground "LightSteelBlue" :underline t :slant italic :weight bold))))
     (mumamo-border-face-out ((t (:italic t :bold t :foreground "LightSteelBlue" :slant italic :weight bold))))
     (next-error ((t (:background "blue3"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "LightGoldenrod"))))
     (nxml-attribute-prefix ((t (:foreground "LightSteelBlue"))))
     (nxml-attribute-value ((t (:foreground "LightSalmon"))))
     (nxml-attribute-value-delimiter ((t (:foreground "LightSalmon"))))
     (nxml-cdata-section-CDATA ((t (:foreground "LightSteelBlue"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "Aquamarine"))))
     (nxml-char-ref-number ((t (:foreground "Aquamarine"))))
     (nxml-comment-content ((t (:foreground "chocolate1"))))
     (nxml-comment-delimiter ((t (:foreground "chocolate1"))))
     (nxml-delimited-data ((t (:foreground "LightSalmon"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "LightSkyBlue"))))
     (nxml-element-prefix ((t (:foreground "LightSteelBlue"))))
     (nxml-entity-ref-delimiter ((t (:foreground "Aquamarine"))))
     (nxml-entity-ref-name ((t (:foreground "Aquamarine"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc" :family "fixed"))))
     (nxml-hash ((t (:foreground "LightSteelBlue"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "LightSteelBlue"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "LightGoldenrod"))))
     (nxml-namespace-attribute-value ((t (:foreground "LightSalmon"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "LightSalmon"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "LightSteelBlue"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box 1 :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 123 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (nxml-outline-ellipsis ((t (:bold t :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 123 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (nxml-outline-indicator ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 123 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (nxml-processing-instruction-content ((t (:foreground "LightSalmon"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "Cyan1"))))
     (nxml-prolog-keyword ((t (:foreground "Cyan1"))))
     (nxml-prolog-literal-content ((t (:foreground "LightSalmon"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "LightSalmon"))))
     (nxml-ref ((t (:foreground "Aquamarine"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-column-dateline ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 1 :family "default"))))
     (org-agenda-date ((t (nil))))
     (org-agenda-date-weekend ((t (:bold t :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 1 :family "default"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "LightSkyBlue"))))
     (org-level-2 ((t (:foreground "LightGoldenrod"))))
     (org-level-3 ((t (:foreground "Cyan1"))))
     (org-level-4 ((t (:foreground "chocolate1"))))
     (org-level-5 ((t (:foreground "PaleGreen"))))
     (org-level-6 ((t (:foreground "Aquamarine"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "LightSalmon"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-property-value ((t (nil))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70" :underline t))))
     (org-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (outline-1 ((t (:foreground "LightSkyBlue"))))
     (outline-2 ((t (:foreground "LightGoldenrod"))))
     (outline-3 ((t (:foreground "Cyan1"))))
     (outline-4 ((t (:foreground "chocolate1"))))
     (outline-5 ((t (:foreground "PaleGreen"))))
     (outline-6 ((t (:foreground "Aquamarine"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "LightSalmon"))))
     (proced-mark ((t (:foreground "Aquamarine"))))
     (proced-marked ((t (:bold t :foreground "Pink" :weight bold))))
     (proced-sort-header ((t (:foreground "Cyan1"))))
     (query-replace ((t (:bold t :background "dark blue" :weight bold))))
     (rcirc-bright-nick ((t (:foreground "Aquamarine"))))
     (rcirc-keyword ((t (:background "darkolivegreen"))))
     (rcirc-my-nick ((t (:foreground "LightSkyBlue"))))
     (rcirc-nick-in-message ((t (:foreground "Cyan1"))))
     (rcirc-nick-in-message-full-line ((t (:bold t :weight bold))))
     (rcirc-other-nick ((t (:foreground "LightGoldenrod"))))
     (rcirc-prompt ((t (:foreground "cyan1"))))
     (rcirc-server ((t (:foreground "chocolate1"))))
     (rcirc-server-prefix ((t (:foreground "chocolate1"))))
     (rcirc-track-keyword ((t (:bold t :weight bold))))
     (rcirc-track-nick ((t (nil))))
     (rcirc-url ((t (:bold t :weight bold))))
     (region ((t (:foreground nil :background "#233323"))))
     (rng-error ((t (:bold t :foreground "Pink" :weight bold))))
     (rngalt-validation-header-bottom ((t (:background "RGB:87/CE/FA" :foreground "white"))))
     (rngalt-validation-header-top ((t (:background "white" :foreground "RGB:87/CE/FA"))))
     (rst-level-1-face ((t (:background "grey85"))))
     (rst-level-2-face ((t (:background "grey78"))))
     (rst-level-3-face ((t (:background "grey71"))))
     (rst-level-4-face ((t (:background "grey64"))))
     (rst-level-5-face ((t (:background "grey57"))))
     (rst-level-6-face ((t (:background "grey50"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (sgml-namespace ((t (:foreground "LightSteelBlue"))))
     (sh-escaped-newline ((t (:foreground "LightSalmon"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "dark blue"))))
     (show-paren-mismatch ((t (:background "dark red"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (textile-acronym-face ((t (:foreground "cyan"))))
     (textile-alignments-face ((t (:foreground "cyan"))))
     (textile-blockquote-face ((t (:foreground "ivory4"))))
     (textile-citation-face ((t (:italic t :slant italic))))
     (textile-class-face ((t (:foreground "yellow green"))))
     (textile-code-face ((t (:foreground "ivory3"))))
     (textile-deleted-face ((t (:strike-through t))))
     (textile-emph-face ((t (:italic t :slant italic))))
     (textile-footnote-face ((t (:foreground "orange red"))))
     (textile-footnotemark-face ((t (:foreground "orange red"))))
     (textile-h1-face ((t (:bold t :weight bold :height 2.0))))
     (textile-h2-face ((t (:bold t :weight bold :height 1.75))))
     (textile-h3-face ((t (:bold t :weight bold :height 1.6))))
     (textile-h4-face ((t (:bold t :weight bold :height 1.35))))
     (textile-h5-face ((t (:bold t :weight bold :height 1.2))))
     (textile-h6-face ((t (:bold t :weight bold :height 1.0))))
     (textile-image-face ((t (:foreground "pink"))))
     (textile-inserted-face ((t (:underline t))))
     (textile-lang-face ((t (:foreground "sky blue"))))
     (textile-link-face ((t (:foreground "blue"))))
     (textile-ol-bullet-face ((t (:foreground "red"))))
     (textile-pre-face ((t (:foreground "green"))))
     (textile-span-face ((t (:foreground "pink"))))
     (textile-strong-face ((t (:bold t :weight bold))))
     (textile-style-face ((t (:foreground "sandy brown"))))
     (textile-subscript-face ((t (:height 0.8))))
     (textile-superscript-face ((t (:height 1.1))))
     (textile-table-face ((t (:foreground "red"))))
     (textile-ul-bullet-face ((t (:foreground "blue"))))
     (tmm-inactive ((t (:foreground "grey70"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
     (trailing-whitespace ((t (:background "red1"))))
     (tty-format-overline ((t (:overline t))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "grey24" :foreground "aquamarine3"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:foreground "darkgray" :weight normal))))
     (whitespace-space ((t (:background "grey20" :foreground "aquamarine3"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "grey22" :foreground "aquamarine3"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition ((t (:foreground "orange"))))
     (woman-bold ((t (:bold t :foreground "green2" :weight bold))))
     (woman-italic ((t (:italic t :underline t :slant italic))))
     (woman-italic-no-ul ((t (:underline nil))))
     (woman-unknown ((t (:foreground "cyan1"))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/mirror-highlight-face ((t (:background "gray22")))))))
