set-option -g default-shell /usr/bin/fish

set -g status off
set-option -g history-limit 50000
set-option -g word-separators ' -_@/\\'

set-option -g prefix C-q
unbind C-b
unbind -a -T prefix
unbind -a -T root
unbind -a -T copy-mode
bind-key C-q send-prefix
bind r source-file ~/.tmux.conf
bind -n C-Space copy-mode
bind -n M-Up     copy-mode \; send-keys -X previous-prompt
bind -n M-Down   copy-mode \; send-keys -X next-prompt
bind -n S-PageUp     copy-mode -u
bind -n S-PageDown   copy-mode -d
bind -n C-f          copy-mode \; command-prompt -i -I "#{pane_search_string}" -p "(search down)" "send -X search-backward-incremental \"%%%\""

set -g escape-time 0
copy_command="xsel -b"
bind -T copy-mode Escape send-keys -X cancel
bind -T copy-mode Up     send -X cursor-up
bind -T copy-mode Down   send -X cursor-down
bind -T copy-mode Left   send -X cursor-left
bind -T copy-mode Right  send -X cursor-right
bind -T copy-mode Home   send-keys -X start-of-line
bind -T copy-mode End    send-keys -X end-of-line
bind -T copy-mode PageUp   send-keys -X page-up
bind -T copy-mode PageDown send-keys -X page-down
bind -T copy-mode S-PageUp   send-keys -X page-up
bind -T copy-mode S-PageDown send-keys -X page-down
bind -T copy-mode C-Home send-keys -X history-top
bind -T copy-mode C-End  send-keys -X history-bottom
bind -T copy-mode C-Left send-keys -X previous-word
bind -T copy-mode C-Right send-keys -X next-word-end
bind -T copy-mode C-Home send-keys -X history-top
bind -T copy-mode C-End send-keys -X history-bottom
bind -T copy-mode Space  send -X begin-selection
bind -T copy-mode C-Space send -X rectangle-toggle
bind -T copy-mode C-c    send -X copy-pipe "$copy_command"
bind -T copy-mode Enter  send -X copy-pipe-and-cancel "$copy_command"
bind -T copy-mode C-f    command-prompt -i -I "#{pane_search_string}" -p "(search down)" "send -X search-backward-incremental \"%%%\""
bind -T copy-mode M-C-Down send-keys -X search-reverse
bind -T copy-mode M-C-Up   send-keys -X search-again
bind -T copy-mode C-Up send-keys -X previous-paragraph
bind -T copy-mode C-Down send-keys -X next-paragraph
bind -T copy-mode M-Up     send-keys -X previous-prompt
bind -T copy-mode M-Down   send-keys -X next-prompt

# tmux_super_fingers
# set-environment -gr ZED_TERM
set-option -g update-environment ZED_TERM
run-shell ~/.config/tmux/plugins/tmux_super_fingers/tmux_super_fingers.tmux
