BROWSER=browse-url
EDITOR="zeditor --wait"
DEBEMAIL="aleksei.gusev@gmail.com"
DEBFULLNAME="Aleksei Gusev"
PGHOST=localhost
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
MAKEFLAGS="-j16"

# gemini-cli
GEMINI_SANDBOX=podman
SANDBOX_SET_UID_GID=true
SANDBOX_FLAGS="--userns=keep-id"
