;;; dock-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dock.el

(defvar dock-track-urgency-mode nil "\
Non-nil if Dock-Track-Urgency mode is enabled.
See the `dock-track-urgency-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `dock-track-urgency-mode'.")
(custom-autoload 'dock-track-urgency-mode "dock" nil)
(autoload 'dock-track-urgency-mode "dock" "\
Manage the urgent status of the Emacs Dock icon.

When active, this mode provides two key behaviors:
1. It automatically removes urgent status when an Emacs frame gains focus.
2. It prevents setting urgent status if the frame already has focus when
`dock-set-needs-attention' is called.
This provides the expected behavior for a modern GUI application.

This is a global minor mode.  If called interactively, toggle the
`Dock-Track-Urgency mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='dock-track-urgency-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)")
(autoload 'dock-set-needs-attention "dock" "\
Request attention for the Emacs Dock icon.")
(autoload 'dock-remove-needs-attention "dock" "\
Remove the `needs attention' state from the Emacs Dock icon.")
(autoload 'dock-set-count-badge "dock" "\
Set the count badge on the Emacs Dock icon to NUMBER.

(fn NUMBER)")
(autoload 'dock-remove-count-badge "dock" "\
Remove the count badge from the Emacs Dock icon.")
(autoload 'dock-set-progress "dock" "\
Set the progress indicator on the Emacs Dock icon to PROGRESS.
PROGRESS is a number between 0 and 1.

(fn PROGRESS)")
(autoload 'dock-remove-progress "dock" "\
Remove the progress indicator from the Emacs Dock icon.")
(register-definition-prefixes "dock" '("dock-"))

;;; End of scraped data

(provide 'dock-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dock-autoloads.el ends here
