;;; ignoramus-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ignoramus.el

(define-obsolete-variable-alias 'ignoramus-file-endings 'ignoramus-file-basename-endings "\
0.6.0")
(define-obsolete-variable-alias 'ignoramus-file-beginnings 'ignoramus-file-basename-beginnings "\
0.6.0")
(define-obsolete-variable-alias 'ignoramus-file-exact-names 'ignoramus-file-basename-exact-names "\
0.6.0")
(define-obsolete-variable-alias 'ignoramus-file-regexps 'ignoramus-file-basename-regexps "\
0.6.0")
(let ((loads (get 'ignoramus 'custom-loads))) (if (member '"ignoramus" loads) nil (put 'ignoramus 'custom-loads (cons '"ignoramus" loads)) (put 'tools 'custom-loads (cons 'ignoramus (get 'tools 'custom-loads)))))
(let ((loads (get 'ignoramus-patterns 'custom-loads))) (if (member '"ignoramus" loads) nil (put 'ignoramus-patterns 'custom-loads (cons '"ignoramus" loads)) (put 'ignoramus 'custom-loads (cons 'ignoramus-patterns (get 'ignoramus 'custom-loads)))))
(autoload 'ignoramus-matches-datafile "ignoramus" "\
Return non-nil if FILE is used for data storage by a known Lisp library.

This function identifies specific files used for persistence by
tramp, semantic, woman, etc.

If a Lisp library is loaded after ignoramus, its files may not
be recognized, in which case `ignoramus-compute-common-regexps'
maybe called.

FILE-BASENAME may also be given as an optimization, in case the
caller has already computed the basename.

As an optimization, EXPANDED may be set to t to indicate that FILE
has already been expanded.

(fn FILE &optional FILE-BASENAME EXPANDED)")
(autoload 'ignoramus-register-datafile "ignoramus" "\
Register a generated file used for data storage.

This generated file will be ignored by ignoramus.

SYMBOL-OR-STRING may be the name of a symbol to consult, or a
string.  If a symbol, it should refer to a string or list of
strings.

TYPE may be one of 'basename, 'completepath, 'prefix, or
'dirprefix.

Optional UNREGISTER tells ignoramus to forget about
SYMBOL-OR-STRING.

(fn SYMBOL-OR-STRING TYPE &optional UNREGISTER)")
(autoload 'ignoramus-boring-p "ignoramus" "\
Return non-nil if ignoramus thinks FILE is uninteresting.

FILE-BASENAME may also be given as an optimization, in case the
caller has already computed the basename.

As an optimization, EXPANDED may be set to t to indicate that FILE
has already been expanded.

This function does not chase symlinks on FILE (see `file-truename').
It may be changed to do so in the future.  You will probably get
fewer surprises if symlinks in FILE are already resolved.

(fn FILE &optional FILE-BASENAME EXPANDED)")
(autoload 'ignoramus-setup "ignoramus" "\
Turn on ignoring files for all members of sequence ACTIONS.

ACTIONS is optional, and defaults to the value of
`ignoramus-default-actions'.

If ACTIONS contains 'all, turn on ignoring files for all
actions in `ignoramus-known-actions'.

(fn &optional ACTIONS)")
(register-definition-prefixes "ignoramus" '("ignoramus-"))

;;; End of scraped data

(provide 'ignoramus-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ignoramus-autoloads.el ends here
