*
*
** Tue Feb  9 13:01:23 2010 (Добавить mail-notification -u в хук проверки почты или ещё к)
   Добавить mail-notification -u в хук проверки почты или ещё куда в Gnus, чтобы
   было актуальное состояние ящика.
** Thu Feb 18 11:50:17 2010 (Maybe I should set comint-move-point-for-output to 'others g)
   Maybe I should set comint-move-point-for-output to 'others global? I also should
   make investigation in other customizations for compilation buffers.

   [[file:~/src/dotfiles/.emacs.d/site-lisp/autotest/autotest.el::set%20make%20local%20variable%20comint%20move%20point%20for%20output%20others][file:~/src/dotfiles/.emacs.d/site-lisp/autotest/autotest.el::set make local variable comint move point for output others]]
** Thu Mar 11 11:39:31 2010 (Обязательно проверить Xmonad.IndependentScreens.)
   Обязательно проверить Xmonad.IndependentScreens.
** Wed May  5 17:34:21 2010 (Комплишенны в shell-mode можно писать на лиспе. Надо сделать)
   Комплишенны в shell-mode можно писать на лиспе. Надо сделать для rake для
   начала; тут есть опастность, т.к. в zsh они у меня не работают, т.е. надо бы
   чтобы работало и там и там. :)
