[cursor]
style.blinking = "Off"
# style.shape = "Beam"
# thickness = 0.25
# vi_mode_style.shape = "Beam"
# vi_mode_style.thickness = 0.25
# vi_mode_style.blinking = "On"

[font]
size = 10
normal.family = "JetBrainsMono Nerd Font"
# normal.style = "semibold"
# bold.style = "extrabold"
# bold_italic.style = "extrabolditalic"
# italic.style = "bolditalic"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
mouse.enabled = true
mouse.mods = "None"
binding = { key = "O", mods = "Control|Shift" }

[keyboard]
bindings = [
    # Normal Mode
    { action = "CreateNewWindow", key = "T", mods = "Control" },
    { action = "Paste", key = "V", mods = "Control" },
    { chars = "\u001b\u007f", key = "Back", mods = "Control" },
    # # Force Alacritty to send the CSI-u sequence for Shift+Enter
    # { chars = "\u001b[13;2u", key = "Enter", mods = "Shift" },
    # # Force Alacritty to send the CSI-u sequence for Control+Enter
    # { chars = "\u001b[13;5u", key = "Enter", mods = "Control" },
    { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Control" },
    { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Control" },
    { action = "SearchForward", key = "F", mode = "~Alt", mods = "Control" },
    { action = "ToggleViMode", key = "F7", mode = "~Search" },
    { action = "ScrollLineUp", key = "Up", mods = "Shift" },
    { action = "ScrollLineDown", key = "Down", mods = "Shift" },
    { action = "ScrollPageUp", key = "PageUp", mode = "Vi|~Search" },
    { action = "ScrollPageDown", key = "PageDown", mode = "Vi|~Search" },
    { action = "ScrollHalfPageUp", key = "Up", mods ="Control", mode = "Vi|~Search" },
    { action = "ScrollHalfPageDown", key = "Down", mods ="Control", mode = "Vi|~Search" },

    # ctrl-c: copy and remove selection
    { action = "Copy", key = "C", mode = "Vi|~Search", mods = "Control" },
    { action = "ClearSelection", key = "C", mode = "Vi|~Search", mods = "Control" },

    # Copy and Exit Vi Mode
    # { action = "Copy", key = "Return", mode = "Vi|~Search" },
    # { action = "ToggleViMode", key = "Return", mode = "Vi|~Search" },
    # { action = "ScrollToBottom", key = "Return", mode = "Vi|~Search" },

    { action = "SearchDeleteWord", key = "Backspace", mods = "Control", mode = "Search"},
    { action = "SearchClear", key = "A", mods = "Control", mode = "Search"},
    { action = "ToggleNormalSelection", key = "Space", mode = "Vi|~Search", mods = "Control" },
    { action = "ToggleBlockSelection", key = "Enter", mode = "Vi|~Search", mods = "Control" },
    { action = "CenterAroundViCursor", key = "L", mode = "Vi|~Search", mods = "Control" },
    { action = "First", key = "Home", mode = "Vi|~Search", mods = "Shift" },
    { action = "Last", key = "End", mode = "Vi|~Search", mods = "Shift" },
    { action = "FirstOccupied", key = "Home", mode = "Vi|~Search" },
    { action = "Last", key = "End", mode = "Vi|~Search" },
    { action = "SemanticLeft", key = "Left", mode = "Vi|~Search", mods = "Control" },
    { action = "SemanticRightEnd", key = "Right", mode = "Vi|~Search", mods = "Control" },
    { action = "SearchNext", key = "Down", mode = "Vi|~Search", mods = "Control|Alt" },
    { action = "SearchPrevious", key = "Up", mode = "Vi|~Search", mods = "Control|Alt" },
    { action = "SearchForward", key = "F", mode = "Vi|~Search", mods = "Control" },
    # { action = "ParagraphUp", key = "Up", mode = "Vi|~Search", mods = "Control" },
    # { action = "ParagraphDown", key = "Down", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollHalfPageUp", key = "Up", mode = "Vi|~Search", mods = "Control" },
    { action = "ScrollHalfPageDown", key = "Down", mode = "Vi|~Search", mods = "Control" },
    { action = "Open", key = "O", mods = "Control", mode = "Vi|~Search" },
]

[terminal.shell]
program = "/usr/bin/fish"

[window]
dynamic_title = true
padding = { x = 4, y = 4 }


[general]
import = ["~/.config/alacritty/themes/modus-vivendi.toml"]

[colors.search]
matches.foreground = "#000000"
matches.background = "#ffff00"
focused_match.foreground = "#000000"
focused_match.background = "#fd9435"

[terminal]
