;;; nerd-icons-grep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nerd-icons-grep.el

(defvar nerd-icons-grep-mode nil "\
Non-nil if Nerd-Icons-Grep mode is enabled.
See the `nerd-icons-grep-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `nerd-icons-grep-mode'.")
(custom-autoload 'nerd-icons-grep-mode "nerd-icons-grep" nil)
(autoload 'nerd-icons-grep-mode "nerd-icons-grep" "\
Adds nerd-icons to `grep-mode' buffers when `grep-use-headings' is t.

This is a global minor mode.  If called interactively, toggle the
`Nerd-Icons-Grep mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='nerd-icons-grep-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "nerd-icons-grep" '("nerd-icons-grep--"))

;;; End of scraped data

(provide 'nerd-icons-grep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nerd-icons-grep-autoloads.el ends here
