;;; standard-keys-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from standard-keys-mode.el

(autoload 'standard-keys-keyboard-quit "standard-keys-mode" "\
Quit from the current command/action.
This acts like `C-g' but is intended to be used for any other additional
keybindings.

NOTE: This doesn't work if `C-g' is remaped." t)
(autoload 'standard-keys-newline-and-indent-before-point "standard-keys-mode" "\
Like `newline-and-indent', but insert the newline before cursor." t)
(autoload 'standard-keys-move-beginning-of-line-or-indentation "standard-keys-mode" "\
Move point to visible beginning of current logical line or indentation.
If point is already at the beginning of the indentation, point is moved
to the beginning of the line, otherwise it is moved to beginning of the
indentation.

ARG is used like in `move-beginning-of-line'.

(fn ARG)" t)
(autoload 'standard-keys-create-new-buffer "standard-keys-mode" "\
Create a new Untitled empty buffer.
The buffer major mode is specified in `standard-keys-new-buffer-mode'." t)
(defvar standard-keys-mode nil "\
Non-nil if Standard-Keys mode is enabled.
See the `standard-keys-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `standard-keys-mode'.")
(custom-autoload 'standard-keys-mode "standard-keys-mode" nil)
(autoload 'standard-keys-mode "standard-keys-mode" "\
Emulate standard keybindings from modern editors.

This is a global minor mode.  If called interactively, toggle the
`Standard-Keys mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='standard-keys-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "standard-keys-mode" '("standard-keys-"))

;;; End of scraped data

(provide 'standard-keys-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; standard-keys-mode-autoloads.el ends here
